### ISSUE TITLE
Zahtevi zadatka se ne poklapaju

### ISSUE THREAD

**Issue by dsheedes** [programiranje2fon/kolokvijum2zadatak3#1]
Zadatak zahteva metodu **unesiVaterpolisteSaTastature** u paketu _vaterpolo.VaterpoloUtakmica_, dok test proverava metodu **ucitajVaterpoliste**

> •Javnu metodu unesiVaterpolisteSaTastature koja sa tastature uÄ�itava podatke o dvadeset dvojici vaterpolista i unosi ih u listu.

> Spisak NEUSPEŠNIH testova:
> 
> 1. U klasi vaterpolo.VaterpoloUtakmica ne postoji metoda ucitajVaterpoliste 
> 	 (proverite naziv metode, povratni tip, tipove i redosled parametara)

**Comment by bojantomic** [comment]
Hvala na ispravci, tekst zadatka prepravljen, metoda je sad ucitajVaterpoliste.
